runtime: go
api_version: go1

handlers:
- url: /favicon\.ico
  static_files: public/images/favicon.ico
  upload: public/images/favicon\.ico
  secure: always

- url: /public
  static_dir: public
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /.*
  script: _go_app

skip_files:
# Default patterns skipped by App Engine, which must be repeated since
# specifying skip_files overrides them otherwise.  See
# https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
# Build files that have no effect in App Engine's runtime.
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^gulp\.js
- ^node_modules/(.*/)?
- ^bower_components/(.*/)?
- ^assets/(.*/)?
- ^sources/(.*/)?
